// generated by build_ui.py
#pragma once
#define UI_BASE 56
#define UI_COUNT 148
#define T_gui_tutorial_01_1 56
#define T_gui_tutorial_01_2 57
#define T_gui_tutorial_01_3 58
#define T_gui_tutorial_01_4 59
#define T_gui_tutorial_02a_1 60
#define T_gui_tutorial_02a_2 61
#define T_gui_tutorial_02a_3 62
#define T_gui_tutorial_02a_4 63
#define T_gui_tutorial_02b_1 64
#define T_gui_tutorial_02b_2 65
#define T_gui_tutorial_02b_3 66
#define T_gui_tutorial_02b_4 67
#define T_gui_tutorial_03_1 68
#define T_gui_tutorial_03_2 69
#define T_gui_tutorial_04_1 70
#define T_gui_tutorial_04_2 71
#define T_gui_tutorial_04_3 72
#define T_gui_tutorial_04_4 73
#define T_gui_bg_poly 74
#define T_gui_smiler_logo 75
#define T_gui_thesmiler_logo 76
#define T_gui_ride_button 77
#define T_gui_poly_smilerfacts_main_menu 78
#define T_gui_settings_icon 79
#define T_gui_quit_icon 80
#define T_gui_tips_icon 81
#define T_gui_trophies_icon 82
#define T_gui_exclamation_icon 83
#define T_gui_flatbutton_options 84
#define T_gui_poly_popup_1 85
#define T_gui_poly_popup_1_flipped 86
#define T_gui_yes_button 87
#define T_gui_no_button 88
#define T_gui_button_continue 89
#define T_gui_button_skip 90
#define T_gui_toggle_2_left_options 91
#define T_gui_toggle_2_right_options 92
#define T_gui_toggle_3_bg_options 93
#define T_gui_toggle_3_left_option 94
#define T_gui_toggle_3_mid_option 95
#define T_gui_toggle_3_right_option 96
#define T_gui_pauseButton 97
#define T_gui_pausemenu_icon 98
#define T_gui_BalanceMeter2 99
#define T_balanceOmeterArrow 100
#define T_gui_balancePrompts 101
#define T_boostBarEmpty 102
#define T_boostingBar 103
#define T_boostButtonBoosting 104
#define T_boostButtonGrey 105
#define T_boostButtonRed 106
#define T_gui_scoreArea 107
#define T_gui_multiplier 108
#define T_gui_MarmaliserIcon 109
#define T_gui_marmaliseFillUp 110
#define T_perfect_orbitron 111
#define T_good_orbitron 112
#define T_ok_orbitron 113
#define T_bad_orbitron 114
#define T_gui_credits 115
#define T_gui_PBIcon 116
#define T_gui_please_wait_loading 117
#define T_smile 118
#define T_joy 119
#define T_kitchener 120
#define T_mona 121
#define T_xray 122
#define T_obedience 123
#define T_smiler_static1 124
#define T_smiler_static2 125
#define T_smiler_static3 126
#define T_flames 127
#define T_sparticle 128
#define T_smileTag 129
#define T_hypnosis1 130
#define T_hypnosis4 131
#define T_gasserCloud_Alpha 132
#define T_boss 133
#define T_boss2 134
#define T_gui_bg_Blueprint 135
#define T_BP_callout1 136
#define T_BP_callout2 137
#define T_BP_callout3 138
#define T_BP_callout4 139
#define T_BP_callout5 140
#define T_BP_callout6 141
#define T_BP_callout7 142
#define T_BP_title 143
#define T_BP_HotSpot 144
#define T_splash_art 145
#define T_gui_top_bar_left_yell 146
#define T_gui_top_bar_mid_yell 147
#define T_gui_top_bar_right_yell 148
#define T_gui_poly_bottom_bar_black 149
#define T_gui_poly_bottom_bar_left 150
#define T_gui_poly_bottom_bar_left_yellow 151
#define T_gui_poly_bottom_bar_right_yellow 152
#define T_gui_indoorHeartlineIcon 153
#define T_gui_invertedFirstDrop 154
#define T_gui_butterfly 155
#define T_gui_batwing 156
#define T_gui_camelback 157
#define T_gui_twistToCorner 158
#define T_gui_pretzelLoop 159
#define T_gui_diveLoop 160
#define T_gui_cobraRoll 161
#define T_gui_doubleHeartline 162
#define T_gui_gas_1 163
#define T_gui_gas_2 164
#define T_gui_gas_3 165
#define T_gui_hypno_1 166
#define T_gui_hypno_2 167
#define T_gui_hypno_3 168
#define T_gui_flasher_1 169
#define T_gui_flasher_2 170
#define T_gui_flasher_3 171
#define T_gui_tickler_1 172
#define T_gui_tickler_2 173
#define T_gui_tickler_3 174
#define T_gui_innoc_1 175
#define T_gui_innoc_2 176
#define T_gui_innoc_3 177
#define T_gui_panel_striped_yellow 178
#define T_gui_panel_locked 179
#define T_gui_loopIcon 180
#define T_gui_secretIcon 181
#define T_gui_trophy_popup_black 182
#define T_gui_swipe_arrow_left 183
#define T_checkbox_ticked 184
#define T_checkbox_unticked 185
#define T_trophy_05_JuniorMechanic256 186
#define T_trophy_06_PimpmySpyder256 187
#define T_trophy_07_FullyPimpedSpyder256 188
#define T_trophy_08_ProMechanic256 189
#define T_trophy_09_TiltTrainee256 190
#define T_trophy_10_TiltMaster256 191
#define T_trophy_11_WelcometoJoy256 192
#define T_trophy_12_MarmalisationComplete256 193
#define T_trophy_13_Repetetron256 194
#define T_trophy_14_Sisyphean256 195
#define T_trophy_17_HappyHoarder256 196
#define T_trophy_18_RailRush256 197
#define T_trophy_19_ThrottleThriller256 198
#define T_trophy_20_SmileAlways256 199
#define T_white 200
#define T_font_small 201
#define T_font_title 202
#define T_font_lcd 203
static const short UI_SIZE[UI_COUNT][2] = {
	{ 256, 117 },
	{ 256, 117 },
	{ 256, 117 },
	{ 256, 117 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 128 },
	{ 256, 192 },
	{ 512, 512 },
	{ 296, 122 },
	{ 417, 148 },
	{ 364, 131 },
	{ 122, 85 },
	{ 122, 85 },
	{ 122, 85 },
	{ 122, 85 },
	{ 153, 137 },
	{ 171, 95 },
	{ 235, 97 },
	{ 235, 97 },
	{ 255, 120 },
	{ 255, 121 },
	{ 284, 117 },
	{ 284, 117 },
	{ 199, 71 },
	{ 199, 71 },
	{ 302, 70 },
	{ 302, 70 },
	{ 302, 70 },
	{ 302, 70 },
	{ 114, 83 },
	{ 122, 85 },
	{ 256, 99 },
	{ 98, 128 },
	{ 162, 512 },
	{ 15, 501 },
	{ 256, 256 },
	{ 160, 160 },
	{ 160, 160 },
	{ 160, 160 },
	{ 237, 94 },
	{ 252, 131 },
	{ 256, 256 },
	{ 512, 512 },
	{ 410, 75 },
	{ 254, 75 },
	{ 132, 75 },
	{ 195, 75 },
	{ 130, 130 },
	{ 134, 133 },
	{ 472, 240 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 512, 512 },
	{ 512, 512 },
	{ 512, 512 },
	{ 128, 128 },
	{ 32, 32 },
	{ 128, 128 },
	{ 256, 256 },
	{ 256, 256 },
	{ 32, 32 },
	{ 256, 256 },
	{ 256, 256 },
	{ 512, 384 },
	{ 175, 90 },
	{ 203, 90 },
	{ 203, 90 },
	{ 203, 90 },
	{ 183, 90 },
	{ 183, 90 },
	{ 202, 90 },
	{ 256, 55 },
	{ 32, 32 },
	{ 512, 256 },
	{ 1024, 120 },
	{ 1024, 120 },
	{ 1024, 120 },
	{ 1024, 116 },
	{ 1024, 116 },
	{ 327, 117 },
	{ 375, 106 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 294, 512 },
	{ 294, 512 },
	{ 256, 256 },
	{ 256, 256 },
	{ 394, 101 },
	{ 42, 66 },
	{ 47, 48 },
	{ 47, 48 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 256, 256 },
	{ 8, 8 },
	{ 256, 256 },
	{ 512, 256 },
	{ 256, 256 },
};
